#include "monty.h"

/**
 * pint - print the number on the top of the stack
 * @stack: the stack generated by the monty bytecode @file
 * @ln: line number currently being operated on @file
 */
void pint(stack_t **stack, unsigned int ln)
{
	if (*stack)
		printf("%i\n", (*stack)->n);
	else
	{
		fprintf(stderr, "L%d: can't pint, stack empty\n", ln);
		fclose(file);
		free_dlistint(*stack);
		exit(EXIT_FAILURE);
	}
}
