#include "monty.h"

/**
 * swap - swaps the two elements on the  top of the stack
 * @stack: the stack generated by the monty bytecode @file
 * @ln: line number currently being operated on @file
 */
void swap(stack_t **stack, unsigned int ln)
{
	int a, b;

	if ((!*stack) || !(*stack)->next)
	{
		fprintf(stderr, "L%d: can't swap, stack too short\n", ln);
		free(file);
		free_dlistint(*stack);
		exit(EXIT_FAILURE);
	}

	a = (*stack)->n;
	b = (*stack)->next->n;
	(*stack)->n = b;
	(*stack)->next->n = a;
}
